import type { TranscriptSource } from "@/api/types"

export const TRANSCRIPT_SOURCES: Record<TranscriptSource, { label: string; hint: string }> = {
  manual: { label: "Uploaded transcript", hint: "Uploaded by the channel." },
  auto: {
    label: "Auto-generated transcript",
    hint: "Generated by YouTube. Names and numbers can be wrong.",
  },
}
